server:
  port: 9292

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ops
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: grp-1
