spring:
  datasource:
    url: jdbc:postgresql://192.168.1.50:5433/ops
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kameshkamesh12345@gmail.com
    password: hvinsssqfulwwgio
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


